### ISSUE TITLE
obolib-obo2owl revision 71 conversion fails

### ISSUE THREAD

**Issue by GoogleCodeExporter** [owlcollab/oboformat#9]
```


What steps will reproduce the problem?
1. obolib-obo2owl revision 71, conversion of caro.obo revision 1.5 (obo 
sourceforge CVS) fails with error:

log4j:WARN No such property [maxFileSize] in org.apache.log4j.FileAppender.
processing arg: /repositories/OBO_CVS/obo/ontology/anatomy/caro/caro.obo
processing arg: -o
Exception in thread "main" java.lang.NullPointerException
    at org.obolibrary.obo2owl.Owl2Obo.getIdentifier(Owl2Obo.java:557)
    at org.obolibrary.obo2owl.Owl2Obo.getOntologyId(Owl2Obo.java:426)
    at org.obolibrary.cli.OBORunner.main(OBORunner.java:161)




2. But conversion using revision 62 works fine



```

Original issue reported on code.google.com by `dosu...@gmail.com` on 26 Feb 2011 at 10:58

**Comment by GoogleCodeExporter** [comment]
```
Sorry. Realized this is a non-issue. This just seems to be change in 
requirement for header tag:value pair 'ontology: namespace'.  Kinda obvious 
from the classes named in the STDERR I guess.

 I'd close the ticket, but it doesn't look like I have the privileges to be able to do so.
```

Original comment by `dosu...@gmail.com` on 27 Feb 2011 at 11:12

**Comment by GoogleCodeExporter** [comment]
```
I'll leave this open as we clearly need clearer error messages.

also the fact it's owl2obo seems odd..
```

Original comment by `cmung...@gmail.com` on 28 Feb 2011 at 9:22

**Comment by GoogleCodeExporter** [comment]
Original comment by `shahid.m...@gmail.com` on 16 Jun 2011 at 6:12
